### ISSUE TITLE
Why can't we just use npm?

### ISSUE THREAD

**Issue by emil14** [JsOS-Team/NPI-pkg#1]
If JavaScript in "JsOs" is am operating system programming language, then why can't we use npm?
Like "NodeOS" guys.

**Comment by imachug** [comment]
We can't use npm because npm relies on filesystem and some libraries which don't exist in JsOS (or runtime.js)

**Comment by PROPHESSOR** [comment]
To be more precise, I would not want to clog the npm of the JsOS applications.
We can use npm packages in the JsOS, but we can't use the JsOS applications in the Node.js

**Comment by emil14** [comment]
@imachug Do you know how NodeOS guys achieved npm usage?
@PROPHESSOR I see, but maybe we could use npm's namespace scope feature to avoid conflicts with NodeJS ecosystem

**Comment by emil14** [comment]
Okay, I got your point
